### ISSUE TITLE
Footer issue filing ... issue

### ISSUE THREAD

**Issue by vortexing** [fhdsl/code_review#2]
In the footer of these OTTR sites the bit at the bottom of the page where you can file a GitHub Issue links back to the OTTR template at JHUDSL.  Perhaps that should be smarter somehow and actually send the user back to the github repo that is driving the actual site???

**Comment by cansavvy** [comment]
Oh yup, I forgot to update that URL. Good catch. I'll fix it to go somewhere more useful.

**Comment by kweav** [comment]
Should be addressed and fixed with PR #4
